"""Home-dashboard widget — embeds the facility map SPA in a NetBox dashboard card.

The map is a full-screen single-page app (`MapView` → `index.html`), not a server-rendered
panel, so the widget surfaces it the cheap, robust way: an `<iframe>` of the existing view.
Being same-origin, the iframe inherits the user's NetBox session, so the SPA's ORM-backed
auth and authenticated `media_url` images work with no extra plumbing — there is no second
rendering path or API token to maintain. The iframe always loads `?embed=1`, which puts the
SPA in its static mode (read by `MapView`): no chrome, no side panel, no in-card breadcrumbs,
and the map fitted to fill the card. Clicking a building still drills in — since the chrome-free
card has no breadcrumbs to return through, the SPA opens the full map in the top window,
deep-linked at that building, rather than navigating inside the card. Two opt-in config toggles
relax the rest — `&interactive=1` re-enables pan/zoom and `&legend=1` shows the "All buildings"
list — both off by default. An optional deep-link hash pins a specific building/floor.

The iframe is sized to the map's **own aspect ratio** (read from the rendered manifest's
siteplan `w`/`h`) via CSS `aspect-ratio`, so the largest map-shaped box that fits the
grid-sized card body is shown — no scroll, no dead space — and it re-fits for free when the
card is resized. Before any facility is imported (no manifest), it falls back to a plain fill.
"""

import json

from django import forms
from django.urls import reverse
from django.utils.html import format_html

from extras.dashboard.widgets import DashboardWidget, WidgetConfigForm, register_widget

from .storage import MANIFEST_NAME, work_dir


@register_widget
class FacilityMapWidget(DashboardWidget):
    default_title = 'Facility Map'
    description = 'Interactive siteplan → building → floor → room map.'
    width = 12
    height = 10   # gridstack rows; the iframe auto-fits the card, so this just sets the opening size

    class ConfigForm(WidgetConfigForm):
        interactive = forms.BooleanField(
            required=False, initial=False,
            help_text='Allow pan & zoom inside the card (off = a fixed, fitted map).',
        )
        show_legend = forms.BooleanField(
            required=False, initial=False,
            help_text='Show the "All buildings" list beside the siteplan.',
        )
        link = forms.CharField(
            required=False,
            help_text='Optional deep-link, e.g. #/b/<dir> or #/f/<dir>/<fid>. Blank opens the siteplan.',
        )

    def _siteplan_ratio(self):
        """``(w, h)`` of the siteplan from the rendered manifest, or ``None`` when it
        can't be read. The manifest is a build artifact (absent before the first import,
        regenerated by every ``build``), so any read/parse error falls back to None."""
        try:
            siteplan = json.loads((work_dir() / MANIFEST_NAME).read_text()).get('siteplan') or {}
            w, h = int(siteplan['w']), int(siteplan['h'])
        except (OSError, ValueError, TypeError, KeyError, json.JSONDecodeError):
            return None
        return (w, h) if w > 0 and h > 0 else None

    def render(self, request):
        config = self.config
        # Always embedded (chrome-free, no navigation); pan/zoom and the building list are opt-in.
        src = reverse('plugins:netbox_facilitymap:map') + '?embed=1'
        if config.get('interactive'):
            src += '&interactive=1'
        if config.get('show_legend'):
            src += '&legend=1'
        # The hash fragment must follow the querystring; the SPA router decodes each segment.
        link = (config.get('link') or '').strip()
        if link:
            src += link if link.startswith('#') else '#' + link.lstrip('/')
        # Size the iframe to the map's aspect ratio so it fills the card with no scroll and
        # minimal dead space: width:100% + aspect-ratio + max-height:100% is the largest
        # map-shaped box that fits the (grid-sized) card body, and the flex wrapper centres it
        # when a dimension is letterboxed. CSS recomputes it on every card resize. With no
        # manifest yet, fall back to a plain fill so the card stays usable.
        ratio = self._siteplan_ratio()
        if ratio:
            box = ('display:block;border:0;width:100%;aspect-ratio:{}/{};'
                   'max-height:100%;margin-inline:auto').format(*ratio)
        else:
            box = 'display:block;border:0;width:100%;height:100%'
        return format_html(
            '<div style="height:100%;display:flex;align-items:center;justify-content:center">'
            '<iframe src="{}" title="Facility Map" loading="lazy" style="{}"></iframe></div>',
            src, box,
        )
