#!/usr/bin/env bash
# start.sh — launch the local annotation tool server.
# Runs server.py from this directory (stdlib-only Python 3). Ctrl-C to stop.
set -euo pipefail

cd "$(dirname "$0")"

# Pick a Python 3 interpreter.
PYTHON="$(command -v python3 || command -v python || true)"
if [ -z "$PYTHON" ]; then
  echo "error: python3 not found on PATH" >&2
  exit 1
fi

# config.json holds the NetBox url/token/port and is required to boot.
if [ ! -f config.json ]; then
  echo "error: config.json is missing (NetBox url/token/port)." >&2
  echo "       create it before starting the server." >&2
  exit 1
fi

# manifest.json + images/ are generated by preprocess.py; warn if absent.
if [ ! -f manifest.json ]; then
  echo "note: manifest.json not found — run '$PYTHON preprocess.py' once first." >&2
fi

# Stop any stale server already bound to our port, so a restart never collides
# with an old instance. config.json sets the port (default 8765); fuser exits
# non-zero when nothing is listening — that's fine under set -e.
PORT="$("$PYTHON" -c "import json;print(json.load(open('config.json')).get('port',8765))" 2>/dev/null || echo 8765)"
if fuser -k "${PORT}/tcp" 2>/dev/null; then
  echo "stopped a previous server on port ${PORT}." >&2
  sleep 1  # give the OS a moment to release the socket before we rebind
fi

exec "$PYTHON" server.py
